 classdef Constants

 % Copyright 2025, The MathWorks, Inc.

     properties (Constant)

        % Structured-string syntax
        PathSep = "/";
        URISep = "/";
        ParamStart = "?";
        ParamSep = "&";
        SchemeSuffix = ":";
        AuthorityPrefix = "//";
        ExtSep = ".";
        FragStart = "#";

        DefaultPersistVar = "xyzzy";

        % HTTP session ID - RFC 7329
        SessionIDPrefix = "SID";
        SessionIDSep = ":";
        SessionIDType = "MathWorks-Data-Pipeline";
        SessionIDHeader = "Session-ID";
        SessionIDPattern = ...
            prodserver.mcp.internal.Constants.SessionIDPrefix + ...
            prodserver.mcp.internal.Constants.SessionIDSep + ...
            prodserver.mcp.internal.Constants.SessionIDType + ...
            prodserver.mcp.internal.Constants.SessionIDSep + ...
            asManyOfPattern(wildcardPattern(Except=prodserver.mcp.internal.Constants.SessionIDSep)) + ...
            prodserver.mcp.internal.Constants.SessionIDSep + ...
            wildcardPattern(36);

        % Session ID at the end of an HTTP path
        SessionIDAtEnd = lookBehindBoundary(...
            prodserver.mcp.internal.Constants.URISep) + ...
            prodserver.mcp.internal.Constants.SessionIDPrefix + ...
            prodserver.mcp.internal.Constants.SessionIDSep + ...
            wildcardPattern(Except=prodserver.mcp.internal.Constants.URISep) + ...
            textBoundary("end");

        % Single hexadecimal digit
        hexPattern = digitsPattern(1) | characterListPattern("ABCDEFabcdef");
        % Percent-encoded character pattern
        percentPattern = "%" + prodserver.mcp.internal.Constants.hexPattern + ...
            prodserver.mcp.internal.Constants.hexPattern;

        % Variables stored in the workspace only -- no persistence.
        WorkspaceScheme = "workspace:"

        % Scheme name, per RFC 3986.  
        % scheme = ALPHA *( ALPHA / DIGIT / "+" / "-" / "." )
        SchemeName = lettersPattern(1) + optionalPattern(...
            asManyOfPattern(alphanumericsPattern(1) | "+" | "." | "-"));

        SchemeNamePattern = textBoundary("start") + ...
            prodserver.mcp.internal.Constants.SchemeName;

        % Scheme prefix: <name>:
        SchemePattern = textBoundary("start") + ...
            prodserver.mcp.internal.Constants.SchemeName + ...
            prodserver.mcp.internal.Constants.SchemeSuffix;

        % Port and component names are valid MATLAB identifiers - a letter
        % followed by any number of letters, digits and underscores.
        NamePattern = (lettersPattern(1) | "_" ) + ...
            asManyOfPattern(alphanumericsPattern(1) | "_");

        % Match a file name extension
        ExtensionPattern = "." + wildcardPattern(Except=".");

        % Match the base name in a path
        BaseNamePattern = lookBehindBoundary(textBoundary("start") + ...
            optionalPattern(...
                asManyOfPattern(wildcardPattern) + ...
                prodserver.mcp.internal.Constants.PathSep)) + ...
            prodserver.mcp.internal.Constants.NamePattern + ...
            lookAheadBoundary(...
                optionalPattern(prodserver.mcp.internal.Constants.ExtensionPattern) + ...
                textBoundary("end"));

        % Match the last string in a qualified name.
        EndOfNamePattern = optionalPattern(lookBehindBoundary( ...
                prodserver.mcp.internal.Constants.PathSep)) + ...
            prodserver.mcp.internal.Constants.NamePattern + ...
            lookAheadBoundary(textBoundary("end"));

        % Match a qualified name. Do not match if there are no occurrences
        % of PathSep even though such names are valid. They are not
        % "qualified". Match any string that ends with "/<NamePattern>".
        QualifiedNamePattern = textBoundary("start") + wildcardPattern() + ...
            prodserver.mcp.internal.Constants.PathSep + ...
            prodserver.mcp.internal.Constants.NamePattern + ...
            textBoundary("end");

    end
end
