function shadowDir = generateShadow(fcns)
%generateShadow Create shadow wrapper functions for schema observation.
%   Generates varargin/varargout wrappers in a temporary folder and returns
%   the folder path. Each wrapper records argument schemas via the
%   SchemaObserver stored in getappdata(0), then forwards to the original
%   function via a pre-bound handle also stored in appdata.

% Copyright 2026 The MathWorks, Inc.

    import prodserver.mcp.internal.metafunction

    shadowDir = fullfile(tempdir, "mcp_schema_shadow_" + ...
        char(matlab.lang.internal.uuid));
    mkdir(shadowDir);

    for i = 1:numel(fcns)
        fcnName = fcns(i);
        mf = metafunction(fcnName);

        % Collect positional input argument names.
        % Positional = no GroupName (both required and optional-positional).
        % NVP names are read from varargin at runtime, not baked in.
        inputNames = string.empty;
        for p = 1:numel(mf.Signature.Inputs)
            if strlength(string(mf.Signature.Inputs(p).Identifier.GroupName)) == 0
                inputNames(end+1) = string(mf.Signature.Inputs(p).Identifier.Name); %#ok<AGROW>
            end
        end
        nPositional = numel(inputNames);

        % Collect output argument names (always positional in MATLAB)
        outputNames = arrayfun(@(p) string(p.Identifier.Name), ...
            mf.Signature.Outputs);

        % Generate the shadow function code
        code = generateCode(fcnName, ...
            inputNames, nPositional, outputNames, numel(outputNames));

        % Write to file
        filePath = fullfile(shadowDir, fcnName + ".m");
        fid = fopen(filePath, 'w');
        fprintf(fid, '%s', code);
        fclose(fid);
    end
end

function code = generateCode(fcnName, inputNames, nPositional, ...
    outputNames, nOutputPositional)

    % Format argument name arrays as string literals
    inNamesStr = formatStringArray(inputNames);
    outNamesStr = formatStringArray(outputNames);

    code = sprintf([...
        'function [varargout] = %s(varargin)\n' ...
        '    flagKey = ''mcp__inCall__%s'';\n' ...
        '    if getappdata(0, flagKey)\n' ...
        '        realFcn = getappdata(0, ''mcp__realHandle__%s'');\n' ...
        '        [varargout{1:nargout}] = realFcn(varargin{:});\n' ...
        '        return\n' ...
        '    end\n' ...
        '    setappdata(0, flagKey, true);\n' ...
        '    try\n' ...
        '        obs = getappdata(0, ''MCPSchemaObserver'');\n' ...
        '        obs.record("%s", "input", %s, varargin, %d);\n' ...
        '        realFcn = getappdata(0, ''mcp__realHandle__%s'');\n' ...
        '        [varargout{1:nargout}] = realFcn(varargin{:});\n' ...
        '        obs.record("%s", "output", %s, varargout, %d);\n' ...
        '    catch ME\n' ...
        '        setappdata(0, flagKey, false);\n' ...
        '        rethrow(ME);\n' ...
        '    end\n' ...
        '    setappdata(0, flagKey, false);\n' ...
        'end\n'], ...
        fcnName, ...
        fcnName, ...
        fcnName, ...
        fcnName, inNamesStr, nPositional, ...
        fcnName, ...
        fcnName, outNamesStr, nOutputPositional);
end

function s = formatStringArray(names)
    if isempty(names)
        s = 'string.empty';
    elseif numel(names) == 1
        s = '"' + names(1) + '"';
    else
        quoted = arrayfun(@(n) '"' + n + '"', names);
        s = '[' + strjoin(quoted, ',') + ']';
    end
end
