function [ctf,endpoint] = buildWireEncodingServer(opts)
%buildWireEncodingServer Build the Wire Encoding demonstration MCP server.
%   ctf = buildWireEncodingServer() builds the server without deploying.
%
%   [ctf,endpoint] = buildWireEncodingServer(host="myserver") builds and
%       deploys to the given host at the default port (9910).
%
%   [ctf,endpoint] = buildWireEncodingServer(port=9920) builds and deploys
%       to localhost at the given port.
%
%   [ctf,endpoint] = buildWireEncodingServer(host="myserver",port=9920)
%       builds and deploys to the given host and port.
%
% This example demonstrates five engineering tools that require the MCP
% Framework wire encoding format to function correctly. Each tool showcases
% a different limitation of plain JSON for MATLAB numeric data:
%
%   matrixMultiply         - vector/matrix orientation
%   analyzeACCircuit       - complex number output
%   interpolateWithMissing - NaN (missing data) preservation
%   fuseSensors            - integer type dispatch (heterogeneous types)
%   blendImages            - integer type dispatch (saturation semantics)

% Copyright 2026 The MathWorks, Inc.

    arguments
        opts.host string {prodserver.mcp.validation.mustBeHostName} = string.empty
        opts.port double {prodserver.mcp.validation.mustBePortNumber} = double.empty
    end

    thisFolder = fileparts(mfilename("fullpath"));
    projectRoot = fullfile(thisFolder, "..", "..");
    dataFolder = fullfile(projectRoot, "Test", "data", "examples", "WireEncoding");

    % Define data resources. Each CSV file is an MCP resource that an LLM
    % can read to obtain input data for the tools.

    audio_crossover = struct( ...
        'uri', 'mcp://wire-encoding/data/audio-crossover', ...
        'contents', fullfile(dataFolder, "audio_crossover_frequencies.csv"), ...
        'name', 'audio_crossover_frequencies', ...
        'title', 'Audio Crossover Frequency Sweep', ...
        'description', 'Frequency sweep for a 2-way loudspeaker crossover network (R=8 Ohm, L=1.2 mH, C=22 uF). Use with analyzeACCircuit.', ...
        'mimeType', 'text/csv');

    emi_filter = struct( ...
        'uri', 'mcp://wire-encoding/data/emi-filter', ...
        'contents', fullfile(dataFolder, "emi_filter_frequencies.csv"), ...
        'name', 'emi_filter_frequencies', ...
        'title', 'EMI Filter Frequency Sweep', ...
        'description', 'Mains harmonic frequencies for an EMI suppression filter (R=50 Ohm, L=10 mH, C=100 nF). Use with analyzeACCircuit.', ...
        'mimeType', 'text/csv');

    vibration = struct( ...
        'uri', 'mcp://wire-encoding/data/vibration-sensor', ...
        'contents', fullfile(dataFolder, "vibration_sensor.csv"), ...
        'name', 'vibration_sensor', ...
        'title', 'Vibration Sensor with Dropouts', ...
        'description', 'Industrial vibration sensor on rotary compressor bearing housing. 100 samples at 1 kHz with NaN dropout bursts. Use with interpolateWithMissing.', ...
        'mimeType', 'text/csv');

    temperature = struct( ...
        'uri', 'mcp://wire-encoding/data/temperature-logger', ...
        'contents', fullfile(dataFolder, "temperature_logger.csv"), ...
        'name', 'temperature_logger', ...
        'title', 'Temperature Logger with Communication Gaps', ...
        'description', 'Outdoor temperature sensor with cellular modem. 48 hourly readings over 2 days with NaN communication failures. Use with interpolateWithMissing.', ...
        'mimeType', 'text/csv');

    pressure = struct( ...
        'uri', 'mcp://wire-encoding/data/pressure-sensors', ...
        'contents', fullfile(dataFolder, "pressure_sensors.csv"), ...
        'name', 'pressure_sensors', ...
        'title', 'Dual-Resolution Pressure Transducers', ...
        'description', 'Hydraulic pressure from redundant sensors: 8-bit (uint8) and 16-bit (uint16) ADCs measuring the same 2 Hz pump cycle. Use with fuseSensors.', ...
        'mimeType', 'text/csv');

    rangefinder = struct( ...
        'uri', 'mcp://wire-encoding/data/rangefinder', ...
        'contents', fullfile(dataFolder, "rangefinder_sensors.csv"), ...
        'name', 'rangefinder_sensors', ...
        'title', 'Laser and Ultrasonic Range Finder', ...
        'description', 'Distance to target from two sensors: laser (double, meters) and ultrasonic (uint16, millimeters). Use with fuseSensors.', ...
        'mimeType', 'text/csv');

    thermal_A = struct( ...
        'uri', 'mcp://wire-encoding/data/thermal-frame-A', ...
        'contents', fullfile(dataFolder, "thermal_frame_A.csv"), ...
        'name', 'thermal_frame_A', ...
        'title', 'Thermal Camera Frame A', ...
        'description', 'FLIR Lepton ROI (12x10 uint8 pixels): person entering doorway. Use with blendImages for temporal noise reduction.', ...
        'mimeType', 'text/csv');

    thermal_B = struct( ...
        'uri', 'mcp://wire-encoding/data/thermal-frame-B', ...
        'contents', fullfile(dataFolder, "thermal_frame_B.csv"), ...
        'name', 'thermal_frame_B', ...
        'title', 'Thermal Camera Frame B', ...
        'description', 'FLIR Lepton ROI (12x10 uint8 pixels): same scene 100 ms later with motion and thermal noise. Use with blendImages.', ...
        'mimeType', 'text/csv');

    gradient_A = struct( ...
        'uri', 'mcp://wire-encoding/data/gradient-frame-A', ...
        'contents', fullfile(dataFolder, "gradient_frame_A.csv"), ...
        'name', 'gradient_frame_A', ...
        'title', 'Thermal Gradient Frame A', ...
        'description', 'Horizontal Sobel edge detection output (12x10 int16 pixels) of thermal frame. Use with blendImages for temporal smoothing.', ...
        'mimeType', 'text/csv');

    gradient_B = struct( ...
        'uri', 'mcp://wire-encoding/data/gradient-frame-B', ...
        'contents', fullfile(dataFolder, "gradient_frame_B.csv"), ...
        'name', 'gradient_frame_B', ...
        'title', 'Thermal Gradient Frame B', ...
        'description', 'Horizontal Sobel edge detection output (12x10 int16 pixels) of thermal frame, 100 ms after frame A. Use with blendImages.', ...
        'mimeType', 'text/csv');

    resources = [audio_crossover, emi_filter, vibration, temperature, ...
                 pressure, rangefinder, thermal_A, thermal_B, gradient_A, gradient_B];

    % Build the server with all tools and data resources.
    fcn = ["matrixMultiply", "analyzeACCircuit", "interpolateWithMissing", ...
           "fuseSensors", "blendImages"];

    ctf = prodserver.mcp.build(fcn, ...
        archive="WireEncoding", ...
        wrapper=["None","None","None","None","None"], ...
        resource=resources, ...
        folder=fullfile(thisFolder, "deploy"));

    endpoint = "";
    if ~isempty(opts.host) || ~isempty(opts.port)
        host = opts.host;
        if isempty(host)
            host = "localhost";
        end
        port = opts.port;
        if isempty(port)
            port = 9910;
        end
        endpoint = prodserver.mcp.deploy(ctf, host, port);
    end
end
