function parameters = argumentSchema(parameters)
% Extract user-specified schema from comments in the description. 
%
% Allow the following syntax:
%
%   %#schema { "maxItems": 12 }
%   %#schema =x.json
%   %#schema +{ "x-call-by": "value" }
%
% In the first,the JSON schema appears literally. In the second, the JSON
% schema is contained in a file. In the third, the schema is added to
% to schema automatically derived from the MATLAB function. The parser 
% will use the "{" character to distinguish these cases.

% Copyright 2026 The MathWorks, Inc.

    import prodserver.mcp.internal.Constants
    import prodserver.mcp.internal.SchemaInjection
    import prodserver.mcp.internal.SchemaOrigin

    function [schema,inject,line] = findSchema(comment,p)
    % Search the comment lines for p to find a line that specifies the
    % schema for p. May or may not exist. 
        schema = []; line = 0;
        inject = SchemaInjection.Unknown;
        for n = 1:numel(comment)
            if startsWith(comment(n),Constants.Schema)
                % Found on line n
                line = n;

                % Found schema line -- replace or add properties?
                inject = SchemaInjection.Add;
                
                % If the schema source (literal or file) is preceded by an
                % "=", the user wants to COMPLETELY REPLACE (skip) the
                % generated schema. A "+", on the other hand, adds the
                % properties to the generated schema, overwriting any
                % autogenerated properties of the same name.
                if startsWith(comment(n),Constants.Schema + ...
                        whitespacePattern + SchemaInjection.ReplaceToken())
                    inject = SchemaInjection.Replace;
                end

                % Now, is it literal or file-based?
                if contains(comment(n), "{")
                    % Literal schema following the keyword.
                    schema = extractBetween(comment(n), "{", ...
                        textBoundary("end"), Boundaries="inclusive");
                    return;
                else
                    % File path follows the keyword and optional schema
                    % injection action token. File must exist.
                    file = strtrim(extractAfter(comment(n), ...
                        Constants.Schema + optionalPattern(...
                        whitespacePattern + characterListPattern(...
                        SchemaInjection.AddToken() + ...
                        SchemaInjection.ReplaceToken))));

                    if exist(file,"file") == 2
                        % Read all the data
                        schema = readlines(file);
                        % Trim leading and trailing whitespace.
                        schema = strtrim(schema);
                        % Join lines into a single string.
                        schema = strjoin(schema," ");
                    else
                        error("prodserver:mcp:SchemaFileNotFound", ...
                            "Unable to locate schema file %s for parameter %s.", ...
                            file,p)
                    end
                end
            end
        end
    end

    
    % For every parameter...
    param = keys(parameters)';

    % Using try-catch as flow of control only to provide a more
    % intelligible error message if the schema is invalid JSON.
    try
        for p = param
            [json,inject,line] = findSchema(parameters(p).description,p);
            
            if ~isempty(json)
                % Require that the schema data be valid JSON
                schema = jsondecode(json);
                % Add the schema to the parameter description.
                parameters(p).schema.line = line;
                parameters(p).schema.schema = schema;
                parameters(p).schema.inject = inject;

                % Knowing the origin of the schema helps with management of
                % type names. Client schemas must contain only JSON schema 
                % types.
                if inject == SchemaInjection.Add
                    parameters(p).schema.origin = SchemaOrigin.Hybrid;
                elseif inject == SchemaInjection.Replace
                    parameters(p).schema.origin = SchemaOrigin.Client;
                else
                    error("prodserver:mcp:InvalidSchemaInjection", ...
                        "Invalid schema injection type: %s", ...
                        string(inject));
                end  
            else
                parameters(p).schema.origin = SchemaOrigin.Introspection;
            end
        end
    catch me
        if startsWith(me.identifier,"MATLAB:json")
            error("prodserver:mcp:InvalidParameterSchema", ...
                "Invalid schema for parameter '%s': %s", ...
                p,me.message);
        else
            rethrow(me);
        end
    end
end