classdef tSchemaNoBlockGolden < matlab.unittest.TestCase
%tSchemaNoBlockGolden Validate schema() output for no-block functions
%   against golden JSON files. These functions lack argument blocks so
%   mcpDefinition() cannot serve as an oracle.
%
%   Golden files are generated by Test/updateSchemaJsonFiles.m and stored
%   in Test/tools/schemaTools/*_golden.json.
%
%   Comparison strategy:
%   - Structural fields (types, required, min/maxProperties) compared exactly
%   - Descriptions verified non-empty (not exact text, to avoid fragility)
%   - Signatures compared for name, type, kind, order, group (exact)
%   - validation and default fields skipped (JSON round-trip issues)

% Copyright 2026 The MathWorks, Inc.

    properties
        toolsFolder
    end

    methods(TestClassSetup)
        function requireSchemaTools(test)
            rst = test.applyFixture(...
                prodserver.mcp.test.mixin.RequireSchemaTools());
            test.toolsFolder = rst.toolFolder;
        end
    end

    methods(Test)

        function goldenComputeNoBlock(test)
            verifyGolden(test, "schemaComputeNoBlock", ...
                @() callWith(@schemaComputeNoBlock, 3, {1.0, 2.0, 3.0}), ...
                "schemaComputeNoBlock_golden.json");
        end

        function goldenFlexAll5(test)
            verifyGolden(test, "schemaFlexNoBlock", ...
                @() schemaFlexNoBlock(1,2,3,4,5), ...
                "schemaFlexNoBlockAll5_golden.json");
        end

        function goldenFlex2of5(test)
            verifyGolden(test, "schemaFlexNoBlock", ...
                {@() schemaFlexNoBlock(1,2), ...
                 @() schemaFlexNoBlock(1,2,3,4,5)}, ...
                "schemaFlexNoBlock2of5_golden.json");
        end

        function goldenVectorNoBlock(test)
            verifyGolden(test, "schemaVectorNoBlock", ...
                {@() callWith(@schemaVectorNoBlock, 3, {[1,2,3]}), ...
                 @() callWith(@schemaVectorNoBlock, 3, {[1,2,3], 2.0})}, ...
                "schemaVectorNoBlock_golden.json");
        end

        function goldenComplexNoBlock(test)
            verifyGolden(test, "schemaComplexNoBlock", ...
                @() callWith(@schemaComplexNoBlock, 3, {[3,0], [4,1]}), ...
                "schemaComplexNoBlock_golden.json");
        end

        function goldenDatetimeNoBlock(test)
            verifyGolden(test, "schemaDatetimeNoBlock", ...
                @() callWith(@schemaDatetimeNoBlock, 3, {2026, 3, 15}), ...
                "schemaDatetimeNoBlock_golden.json");
        end

        function goldenDurationNoBlock(test)
            verifyGolden(test, "schemaDurationNoBlock", ...
                @() callWith(@schemaDurationNoBlock, 2, {1, 30, 45}), ...
                "schemaDurationNoBlock_golden.json");
        end

        function goldenTableNoBlock(test)
            verifyGolden(test, "schemaTableNoBlock", ...
                @() callWith(@schemaTableNoBlock, 2, {["A","B"], [1,2], "X"}), ...
                "schemaTableNoBlock_golden.json");
        end

        function goldenTimetableNoBlock(test)
            verifyGolden(test, "schemaTimetableNoBlock", ...
                @() callWith(@schemaTimetableNoBlock, 3, ...
                    {[10,20,30], 9, 15}), ...
                "schemaTimetableNoBlock_golden.json");
        end

    end

    methods(Access = private)

        function verifyGolden(test, fcnName, exercises, goldenFileName)
            observed = prodserver.mcp.schema(fcnName, exercises, ...
                encoding="Invertible");
            goldenFile = fullfile(test.toolsFolder, goldenFileName);
            test.assumeTrue(isfile(goldenFile), ...
                "Golden file missing: " + goldenFile + ...
                ". Run updateSchemaJsonFiles(action=""write"") to generate.");
            expected = jsondecode(fileread(goldenFile));

            verifyToolName(test, observed, expected);
            verifySchemaStructure(test, observed.tools.inputSchema, ...
                expected.tools.inputSchema, "inputSchema");
            verifySchemaStructure(test, observed.tools.outputSchema, ...
                expected.tools.outputSchema, "outputSchema");
            verifySignatures(test, observed.signatures, ...
                expected.signatures, fcnName);
            verifyDescriptionsPresent(test, observed);
        end

        function verifyToolName(test, observed, expected)
            test.verifyEqual(string(observed.tools.name), ...
                string(expected.tools.name), "Tool name mismatch");
        end

        function verifySchemaStructure(test, observed, expected, label)
            test.verifyEqual(string(observed.type), ...
                string(expected.type), label + ".type");

            if ~isfield(expected, 'properties')
                return;
            end

            expNames = sort(string(fieldnames(expected.properties)));
            obsNames = sort(string(fieldnames(observed.properties)));
            test.verifyEqual(obsNames, expNames, ...
                label + ": property names");

            for i = 1:numel(expNames)
                name = expNames(i);
                verifyPropertyType(test, ...
                    observed.properties.(name), ...
                    expected.properties.(name), ...
                    label + "." + name);
            end

            if isfield(expected, 'required')
                obsReq = sort(toRow(observed.required));
                expReq = sort(toRow(expected.required));
                test.verifyEqual(obsReq, expReq, label + ".required");
            end

            if isfield(expected, 'minProperties')
                test.verifyEqual(observed.minProperties, ...
                    expected.minProperties, label + ".minProperties");
            end
            if isfield(expected, 'maxProperties')
                test.verifyEqual(observed.maxProperties, ...
                    expected.maxProperties, label + ".maxProperties");
            end
        end

        function verifyPropertyType(test, observed, expected, label)
            obsType = string(observed.type);
            expType = string(expected.type);
            test.verifyEqual(obsType, expType, label + ".type");

            if obsType == "object" && isfield(observed, 'properties') ...
                    && isfield(observed.properties, 'data')
                obsData = observed.properties.data;
                expData = expected.properties.data;
                test.verifyEqual(string(obsData.type), ...
                    string(expData.type), label + ".data.type");
                if isfield(obsData, 'items') && isfield(expData, 'items')
                    test.verifyEqual(string(obsData.items.type), ...
                        string(expData.items.type), ...
                        label + ".data.items.type");
                end
            end
        end

        function verifySignatures(test, observed, expected, fcnName)
            obsSig = observed.(fcnName);
            expSig = expected.(fcnName);

            test.verifyEqual(string(obsSig.function), ...
                string(expSig.function), "signatures.function");

            if isfield(expSig, 'input')
                verifySigGroup(test, obsSig.input, expSig.input, "input");
            end
            if isfield(expSig, 'output')
                verifySigGroup(test, obsSig.output, expSig.output, "output");
            end
        end

        function verifySigGroup(test, observed, expected, label)
            test.verifyEqual(toRow(observed.name), ...
                toRow(expected.name), label + ".name");
            test.verifyEqual(toRow(observed.type), ...
                toRow(expected.type), label + ".type");
            test.verifyEqual(toRow(observed.kind), ...
                toRow(expected.kind), label + ".kind");
            test.verifyEqual(toRow(observed.order), ...
                toRow(expected.order), label + ".order");

            obsGroup = observed.group;
            expGroup = expected.group;
            obsFields = sort(string(fieldnames(obsGroup)));
            expFields = sort(string(fieldnames(expGroup)));
            test.verifyEqual(obsFields, expFields, label + ".group fields");
        end

        function verifyDescriptionsPresent(test, defs)
            test.verifyTrue(strlength(defs.tools.description) > 0, ...
                "Tool description empty");

            schemas = {"inputSchema", "outputSchema"};
            for s = 1:numel(schemas)
                schemaName = schemas{s};
                if isfield(defs.tools.(schemaName), 'properties')
                    props = defs.tools.(schemaName).properties;
                    names = fieldnames(props);
                    for i = 1:numel(names)
                        prop = props.(names{i});
                        test.verifyTrue( ...
                            isfield(prop, 'description') && ...
                            strlength(prop.description) > 0, ...
                            schemaName + "." + names{i} + " description empty");
                    end
                end
            end
        end

    end
end

function callWith(fcn, nout, args)
    [varargout{1:nout}] = fcn(args{:}); %#ok<VARARG>
end

function r = toRow(x)
%toRow Normalize to a row string vector for comparison.
%   Handles char (from jsondecode scalar), cellstr, and string arrays.
    if ischar(x)
        r = string(x);
    elseif iscell(x)
        r = string(x(:))';
    else
        r = string(x(:))';
    end
end
