classdef tHeaders < matlab.unittest.TestCase
% Test HTTP header manipulation

% Copyright 2026 The MathWorks, Inc.

    methods(Test)

        function setHeader(test)

            response = struct(...
                'ApiVersion',[1 0 0], ...
                'HttpCode','200', ...
                'HttpMessage','OK', ...
                'Headers', {{'Server' 'MATLAB Production Server/Model Context Protocol (v1.0)'; ...
                'Content-Length' '0'; ...
                'Content-Type' 'application/json'}});

            len = string(17);
            response.Headers = prodserver.mcp.internal.setHeaderValue(...
                response.Headers,prodserver.mcp.MCPConstants.ContentLength, ...
                {char(len)});

            test.verifyEqual(response.Headers{2,2},char(len));

            ct = 'text/plain';
            headers = [ ...
                matlab.net.http.field.ContentTypeField(ct); 
                matlab.net.http.field.AcceptField('application/octet-stream');
                matlab.net.http.field.ContentLengthField('0');
                matlab.net.http.field.GenericField('Server',...
                'MATLAB Production Server/Model Context Protocol (v1.0)')];
            response.Headers = headers;
            response.Headers = prodserver.mcp.internal.setHeaderValue(...
                response.Headers,prodserver.mcp.MCPConstants.ContentLength, ...
                {char(len)});
            test.verifyEqual(response.Headers(3).Value,len);

        end

        function getHeader(test)

            ct = 'application/json';
            response = struct(...
                'ApiVersion',[1 0 0], ...
                'HttpCode','200', ...
                'HttpMessage','OK', ...
                'Headers', {{'Server' 'MATLAB Production Server/Model Context Protocol (v1.0)'; ...
                'Content-Length' '0'; ...
                'Content-Type' ct}});

            value = prodserver.mcp.internal.getHeaderValue(...
                prodserver.mcp.MCPConstants.ContentType, response.Headers);
            test.verifyEqual(value,ct);

            ct = 'text/plain';
            headers = [ ...
                matlab.net.http.field.ContentTypeField(ct); 
                matlab.net.http.field.AcceptField('application/octet-stream');
                matlab.net.http.field.ContentLengthField('0');
                matlab.net.http.field.GenericField('Server',...
                'MATLAB Production Server/Model Context Protocol (v1.0)')];
          
            value = prodserver.mcp.internal.getHeaderValue(...
                prodserver.mcp.MCPConstants.ContentType, headers);
            test.verifyEqual(value,string(ct));
        end


    end
end
