classdef tWireEncodingServer < matlab.unittest.TestCase
% Integration test: build, deploy and call the WireEncoding MCP server.
%
% Tests all five tools against a running MPS instance, verifying that
% wire encoding correctly preserves vector orientation, complex numbers,
% NaN values, and integer types through the full HTTP round-trip.

% Copyright 2026 The MathWorks, Inc.

    properties
        server
        host
        port
        exampleFolder
        dataFolder
        endpoint
    end

    methods (TestClassSetup)

        function requireActiveServer(test)
            test.server = getenv(prodserver.mcp.MCPConstants.TestServerEnvVar);
            test.assertTrue(~isempty(test.server), ...
                "Set environment variable " + ...
                prodserver.mcp.MCPConstants.TestServerEnvVar + ...
                " to network address of MPS instance for testing.");

            healthQuery = test.server + "/api/health";
            response = webread(healthQuery);
            test.assertTrue(strcmp(response.status, "ok"), ...
                "Invalid response to health query: " + response.status);

            hostPattern = lookBehindBoundary(textBoundary("start") + ...
                wildcardPattern("Except", ":") + "://") + ...
                wildcardPattern("Except", ":") + ...
                lookAheadBoundary(characterListPattern(":/") | ...
                textBoundary("end"));
            test.host = string(extract(test.server, hostPattern));
            portPattern = lookBehindBoundary(wildcardPattern + ...
                test.host + ":") + wildcardPattern + textBoundary("end");
            test.port = string(extract(test.server, portPattern));
        end

        function addExampleToPath(test)
            import matlab.unittest.fixtures.PathFixture

            testFolder = fileparts(mfilename("fullpath"));
            test.exampleFolder = fullfile(testFolder, "..", "..", "..", ...
                "Examples", "WireEncoding");
            test.applyFixture(PathFixture(test.exampleFolder));

            test.dataFolder = fullfile(testFolder, "..", "..", ...
                "data", "examples", "WireEncoding");
        end

        function registerPackage(test)
            import matlab.unittest.fixtures.PathFixture
            testFolder = fileparts(mfilename("fullpath"));
            pkgFolder = fullfile(testFolder, "..", "..", "..");
            test.applyFixture(PathFixture(pkgFolder));
        end

        function buildAndDeploy(test)
            import matlab.unittest.fixtures.TemporaryFolderFixture

            archive = "WireEncodingIntTest";
            test.applyFixture(prodserver.mcp.test.mixin.RemoveArchive( ...
                test.server, archive));

            tfolder = TemporaryFolderFixture;
            applyFixture(test, tfolder);

            resources = buildResources(test);
            fcn = ["matrixMultiply", "analyzeACCircuit", ...
                   "interpolateWithMissing", "fuseSensors", "blendImages"];

            ctf = prodserver.mcp.build(fcn, ...
                archive=archive, ...
                wrapper=["None","None","None","None","None"], ...
                resource=resources, ...
                folder=tfolder.Folder, ...
                encoding="Invertible");
            test.assertNotEmpty(ctf);
            test.assertEqual(exist(ctf, "file"), 2, ctf);

            test.endpoint = prodserver.mcp.deploy(ctf, test.host, test.port);
        end

    end

    methods (Test)

        function toolsExist(test)
            test.verifyTrue( ...
                prodserver.mcp.exist(test.endpoint, "matrixMultiply", "Tool"));
            test.verifyTrue( ...
                prodserver.mcp.exist(test.endpoint, "analyzeACCircuit", "Tool"));
            test.verifyTrue( ...
                prodserver.mcp.exist(test.endpoint, "interpolateWithMissing", "Tool"));
            test.verifyTrue( ...
                prodserver.mcp.exist(test.endpoint, "fuseSensors", "Tool"));
            test.verifyTrue( ...
                prodserver.mcp.exist(test.endpoint, "blendImages", "Tool"));
        end

        function listResources(test)
            resourceList = prodserver.mcp.list(test.endpoint, "Resource");
            % 10 data resources + 1 built-in wire-encoding resource = 11
            test.verifyEqual(numel(resourceList), 11, "Number of resources");
        end

        function callMatrixMultiply_dotProduct(test)
            C = prodserver.mcp.call(test.endpoint, ...
                "matrixMultiply", [1 2 3], [4;5;6]);
            localResult = matrixMultiply([1 2 3], [4;5;6]);
            test.verifyEqual(C, localResult, AbsTol=1e-10);
        end

        function callMatrixMultiply_outerProduct(test)
            C = prodserver.mcp.call(test.endpoint, ...
                "matrixMultiply", [2;3;4], [10 20 30]);
            localResult = matrixMultiply([2;3;4], [10 20 30]);
            test.verifyEqual(C, localResult, AbsTol=1e-10);
        end

        function callMatrixMultiply_matrixTimesVector(test)
            R = [cosd(45) -sind(45) 0; sind(45) cosd(45) 0; 0 0 1];
            v = [1; 0; 0];
            C = prodserver.mcp.call(test.endpoint, ...
                "matrixMultiply", R, v);
            localResult = matrixMultiply(R, v);
            test.verifyEqual(C, localResult, AbsTol=1e-10);
        end

        function callAnalyzeACCircuit_singleFrequency(test)
            [Z_mcp, I_mcp] = prodserver.mcp.call(test.endpoint, ...
                "analyzeACCircuit", 100, 0.1, 10e-6, 60, 120);
            [Z, I, ~, ~, ~] = analyzeACCircuit(100, 0.1, 10e-6, 60, 120);
            test.verifyEqual(real(Z_mcp), real(Z), AbsTol=1e-6);
            test.verifyEqual(imag(Z_mcp), imag(Z), AbsTol=1e-6);
            test.verifyEqual(real(I_mcp), real(I), AbsTol=1e-8);
            test.verifyEqual(imag(I_mcp), imag(I), AbsTol=1e-8);
        end

        function callAnalyzeACCircuit_frequencySweep(test)
            freq = [100;500;1000;5000;10000;20000];
            Z_mcp = prodserver.mcp.call(test.endpoint, ...
                "analyzeACCircuit", 8, 1.2e-3, 22e-6, freq, 10);
            [Z, ~, ~, ~, ~] = analyzeACCircuit(8, 1.2e-3, 22e-6, freq, 10);
            test.verifyEqual(real(Z_mcp), real(Z), AbsTol=1e-6);
            test.verifyEqual(imag(Z_mcp), imag(Z), AbsTol=1e-6);
            test.verifyEqual(numel(Z_mcp), 6);
        end

        function callInterpolateWithMissing_vibration(test)
            data = readtable(fullfile(test.dataFolder, ...
                "vibration_sensor.csv"), "CommentStyle", "#");
            t = data.time_s;
            signal = data.acceleration_g;
            [reconstructed, gapMask] = prodserver.mcp.call(test.endpoint, ...
                "interpolateWithMissing", t, signal, t);
            test.verifyFalse(any(isnan(reconstructed)), ...
                "Output should have no NaN after interpolation");
            test.verifyTrue(gapMask(12), ...
                "Index 12 should be flagged as gap");
            test.verifyTrue(gapMask(13), ...
                "Index 13 should be flagged as gap");
        end

        function callInterpolateWithMissing_temperature(test)
            data = readtable(fullfile(test.dataFolder, ...
                "temperature_logger.csv"), "CommentStyle", "#");
            t = data.hour;
            signal = data.temperature_c;
            t_query = (0:0.5:47)';
            [reconstructed, ~] = prodserver.mcp.call(test.endpoint, ...
                "interpolateWithMissing", t, signal, t_query);
            test.verifyFalse(any(isnan(reconstructed)));
            % Temperature should stay in reasonable range (10-30 C)
            test.verifyGreaterThan(min(reconstructed), 10);
            test.verifyLessThan(max(reconstructed), 30);
        end

        function callFuseSensors_pressure(test)
            data = readtable(fullfile(test.dataFolder, ...
                "pressure_sensors.csv"), "CommentStyle", "#");
            s1 = uint8(data.sensor1_uint8);
            s2 = uint16(data.sensor2_uint16);
            [~, weights] = prodserver.mcp.call(test.endpoint, ...
                "fuseSensors", s1, s2);
            [~, localWeights, ~] = fuseSensors(s1, s2);
            test.verifyEqual(weights, localWeights, AbsTol=1e-6);
            % 16-bit sensor should dominate
            test.verifyGreaterThan(weights(2), 0.99);
        end

        function callFuseSensors_rangefinder(test)
            data = readtable(fullfile(test.dataFolder, ...
                "rangefinder_sensors.csv"), "CommentStyle", "#");
            s1 = data.laser_m;
            s2 = uint16(data.ultrasonic_mm_uint16);
            [~, weights] = prodserver.mcp.call(test.endpoint, ...
                "fuseSensors", s1, s2);
            % Laser (double) should get near-100% weight
            test.verifyGreaterThan(weights(1), 0.99);
        end

        function callBlendImages_thermal(test)
            A = uint8(readmatrix(fullfile(test.dataFolder, ...
                "thermal_frame_A.csv"), "CommentStyle", "#"));
            B = uint8(readmatrix(fullfile(test.dataFolder, ...
                "thermal_frame_B.csv"), "CommentStyle", "#"));
            result = prodserver.mcp.call(test.endpoint, ...
                "blendImages", A, B, 0.6);
            localResult = blendImages(A, B, 0.6);
            test.verifyEqual(result, localResult);
            test.verifyClass(result, 'uint8');
        end

        function callBlendImages_gradient(test)
            A = int16(readmatrix(fullfile(test.dataFolder, ...
                "gradient_frame_A.csv"), "CommentStyle", "#"));
            B = int16(readmatrix(fullfile(test.dataFolder, ...
                "gradient_frame_B.csv"), "CommentStyle", "#"));
            result = prodserver.mcp.call(test.endpoint, ...
                "blendImages", A, B, 0.7);
            localResult = blendImages(A, B, 0.7);
            test.verifyEqual(result, localResult);
            test.verifyClass(result, 'int16');
        end

    end

    methods (Access=private)

        function resources = buildResources(test)
            df = test.dataFolder;

            audio_crossover = struct( ...
                'uri', 'mcp://wire-encoding/data/audio-crossover', ...
                'contents', fullfile(df, "audio_crossover_frequencies.csv"), ...
                'name', 'audio_crossover_frequencies', ...
                'title', 'Audio Crossover Frequency Sweep', ...
                'description', 'Frequency sweep for crossover network.', ...
                'mimeType', 'text/csv');

            emi_filter = struct( ...
                'uri', 'mcp://wire-encoding/data/emi-filter', ...
                'contents', fullfile(df, "emi_filter_frequencies.csv"), ...
                'name', 'emi_filter_frequencies', ...
                'title', 'EMI Filter Frequency Sweep', ...
                'description', 'Mains harmonic frequencies for EMI filter.', ...
                'mimeType', 'text/csv');

            vibration = struct( ...
                'uri', 'mcp://wire-encoding/data/vibration-sensor', ...
                'contents', fullfile(df, "vibration_sensor.csv"), ...
                'name', 'vibration_sensor', ...
                'title', 'Vibration Sensor with Dropouts', ...
                'description', 'Vibration sensor data with NaN dropouts.', ...
                'mimeType', 'text/csv');

            temperature = struct( ...
                'uri', 'mcp://wire-encoding/data/temperature-logger', ...
                'contents', fullfile(df, "temperature_logger.csv"), ...
                'name', 'temperature_logger', ...
                'title', 'Temperature Logger', ...
                'description', 'Temperature readings with communication gaps.', ...
                'mimeType', 'text/csv');

            pressure = struct( ...
                'uri', 'mcp://wire-encoding/data/pressure-sensors', ...
                'contents', fullfile(df, "pressure_sensors.csv"), ...
                'name', 'pressure_sensors', ...
                'title', 'Dual-Resolution Pressure Transducers', ...
                'description', 'Redundant 8-bit and 16-bit pressure sensors.', ...
                'mimeType', 'text/csv');

            rangefinder = struct( ...
                'uri', 'mcp://wire-encoding/data/rangefinder', ...
                'contents', fullfile(df, "rangefinder_sensors.csv"), ...
                'name', 'rangefinder_sensors', ...
                'title', 'Laser and Ultrasonic Range Finder', ...
                'description', 'Distance from laser (double) and ultrasonic (uint16).', ...
                'mimeType', 'text/csv');

            thermal_A = struct( ...
                'uri', 'mcp://wire-encoding/data/thermal-frame-A', ...
                'contents', fullfile(df, "thermal_frame_A.csv"), ...
                'name', 'thermal_frame_A', ...
                'title', 'Thermal Camera Frame A', ...
                'description', '12x10 uint8 thermal pixels.', ...
                'mimeType', 'text/csv');

            thermal_B = struct( ...
                'uri', 'mcp://wire-encoding/data/thermal-frame-B', ...
                'contents', fullfile(df, "thermal_frame_B.csv"), ...
                'name', 'thermal_frame_B', ...
                'title', 'Thermal Camera Frame B', ...
                'description', '12x10 uint8 thermal pixels (100 ms later).', ...
                'mimeType', 'text/csv');

            gradient_A = struct( ...
                'uri', 'mcp://wire-encoding/data/gradient-frame-A', ...
                'contents', fullfile(df, "gradient_frame_A.csv"), ...
                'name', 'gradient_frame_A', ...
                'title', 'Thermal Gradient Frame A', ...
                'description', '12x10 int16 edge detection output.', ...
                'mimeType', 'text/csv');

            gradient_B = struct( ...
                'uri', 'mcp://wire-encoding/data/gradient-frame-B', ...
                'contents', fullfile(df, "gradient_frame_B.csv"), ...
                'name', 'gradient_frame_B', ...
                'title', 'Thermal Gradient Frame B', ...
                'description', '12x10 int16 edge detection (100 ms later).', ...
                'mimeType', 'text/csv');

            resources = [audio_crossover, emi_filter, vibration, temperature, ...
                         pressure, rangefinder, thermal_A, thermal_B, ...
                         gradient_A, gradient_B];
        end

    end
end
