function [ctf,endpoint] = buildMaterialsServer(opts)
%buildMaterialsServer Build the Materials Engineering MCP server.
%   ctf = buildMaterialsServer() builds the server without deploying.
%
%   [ctf,endpoint] = buildMaterialsServer(host="http://myserver:9910")
%       builds and deploys to the given server.
%
% This example demonstrates how MCP Resources enhance the usability of MCP
% tools. The server exposes material property data as resources and
% engineering calculation tools that consume that data.
%
% An LLM using this server can browse available materials, read their
% properties, and pass exact values to the calculation tools -- without
% hallucinating physical constants or requiring the user to supply them.

% Copyright 2026 The MathWorks, Inc.

    arguments
        opts.host string {prodserver.mcp.validation.mustBeHost} = string.empty
    end

    thisFolder = fileparts(mfilename("fullpath"));

    % Define material resources. Each material is a separate resource
    % identified by a unique URI. The catalog resource provides an overview
    % of all available materials.

    catalog = struct( ...
        'uri', 'mcp://materials/catalog', ...
        'contents', fullfile(thisFolder, "material_catalog.json"), ...
        'name', 'material_catalog', ...
        'title', 'Material Catalog', ...
        'description', 'List of all available engineering materials with summaries. Read this first to discover which materials are available.', ...
        'mimeType', 'application/json');

    aluminum = struct( ...
        'uri', 'mcp://materials/aluminum_6061', ...
        'contents', fullfile(thisFolder, "aluminum_6061.json"), ...
        'name', 'aluminum_6061', ...
        'title', 'Aluminum 6061-T6', ...
        'description', 'Mechanical and thermal properties of Aluminum 6061-T6 alloy.', ...
        'mimeType', 'application/json');

    steel = struct( ...
        'uri', 'mcp://materials/steel_304', ...
        'contents', fullfile(thisFolder, "steel_304.json"), ...
        'name', 'steel_304', ...
        'title', 'Stainless Steel 304', ...
        'description', 'Mechanical and thermal properties of Stainless Steel 304.', ...
        'mimeType', 'application/json');

    titanium = struct( ...
        'uri', 'mcp://materials/titanium_ti6al4v', ...
        'contents', fullfile(thisFolder, "titanium_ti6al4v.json"), ...
        'name', 'titanium_ti6al4v', ...
        'title', 'Titanium Ti-6Al-4V', ...
        'description', 'Mechanical and thermal properties of Titanium Ti-6Al-4V alloy.', ...
        'mimeType', 'application/json');

    copper = struct( ...
        'uri', 'mcp://materials/copper_c110', ...
        'contents', fullfile(thisFolder, "copper_c110.json"), ...
        'name', 'copper_c110', ...
        'title', 'Copper C110 (ETP)', ...
        'description', 'Mechanical and thermal properties of Copper C110 (Electrolytic Tough Pitch).', ...
        'mimeType', 'application/json');

    resources = [catalog, aluminum, steel, titanium, copper];

    % Build the server. Package both tools and all material resources into a
    % single MCP server.
    fcn = ["calculateBeamStress", "calculateThermalResistance"];

    ctf = prodserver.mcp.build(fcn, ...
        archive="Materials", ...
        resource=resources, ...
        folder=fullfile(thisFolder, "deploy"));

    % Deploy only if the user supplied host or port. Apply MPS defaults for
    % whichever was not specified.
    endpoint = "";
    if ~isempty(opts.host)
        endpoint = prodserver.mcp.deploy(ctf, opts.host);
    end
end
