function [one,two,three] = toyToolThree(three,two,one)
% I tell you three times. Thrice is nice. Just nonsense.
% And now a haiku to test the fidelity of comment capture:
%    
%    Whispers through the code,
%    Context flows—models connect,
%    Understanding grows.
%
% Brought to you, of course, by an LLM.
    arguments(Input)
        % The first argument has the last name, numerically.
        three string  % First or third?
        % This argument is an immovable object. Whence the 
        % unstoppable force?
        two struct    % Always second.
        % Many words and fewer lines in this comment. 
        % All of it nonsense, just here to make sure that MCP
        % Tools generated by this support package include every line.
        % Literally every line. Can't skip a single one. What if we did?
        % A disaster, no doubt. Who knows what information would be lost?
        % But with this test, we're sure to capture everything.
        one cell      % Still number one!
    end
    arguments(Output)
        one double   % The first of all things
        % One longer comment in the middle of a list of shorter ones.
        % It's a surprise!
        two (1,1) struct   % Clone, doppelganger, twin
        three string % Tripled in size and strength
    end

    three = [ three, three, three ];
    two.too = two.two;
    one = one{1} + 1;
end
