classdef tMaterialsServer < matlab.unittest.TestCase
% Integration test: build, deploy and call the Materials MCP server.

% Copyright 2026 The MathWorks, Inc.

    properties
        server
        host
        port
        exampleFolder
        endpoint
    end

    methods (TestClassSetup)

        function requireActiveServer(test)
            test.server = getenv(prodserver.mcp.MCPConstants.TestServerEnvVar);
            test.assertTrue(~isempty(test.server), ...
                "Set environment variable " + ...
                prodserver.mcp.MCPConstants.TestServerEnvVar + ...
                " to network address of MPS instance for testing.");

            healthQuery = test.server + "/api/health";
            response = webread(healthQuery);
            test.assertTrue(strcmp(response.status, "ok"), ...
                "Invalid response to health query: " + response.status);

            % Extract host and port from server address
            hostPattern = lookBehindBoundary(textBoundary("start") + ...
                wildcardPattern("Except", ":") + "://") + ...
                wildcardPattern("Except", ":") + ...
                lookAheadBoundary(characterListPattern(":/") | ...
                textBoundary("end"));
            test.host = string(extract(test.server, hostPattern));
            portPattern = lookBehindBoundary(wildcardPattern + ...
                test.host + ":") + wildcardPattern + textBoundary("end");
            test.port = string(extract(test.server, portPattern));
        end

        function addExampleToPath(test)
            import matlab.unittest.fixtures.PathFixture

            testFolder = fileparts(mfilename("fullpath"));
            test.exampleFolder = fullfile(testFolder, "..", "..", "..", ...
                "Examples", "Materials");
            test.applyFixture(PathFixture(test.exampleFolder));
        end

        function registerPackage(test)
            import matlab.unittest.fixtures.PathFixture
            testFolder = fileparts(mfilename("fullpath"));
            pkgFolder = fullfile(testFolder, "..", "..", "..");
            test.applyFixture(PathFixture(pkgFolder));
        end

        function buildAndDeploy(test)
            import matlab.unittest.fixtures.TemporaryFolderFixture

            archive = "MaterialsIntTest";
            test.applyFixture(prodserver.mcp.test.mixin.RemoveArchive( ...
                test.server, archive));

            tfolder = TemporaryFolderFixture;
            applyFixture(test, tfolder);

            resources = buildResources(test);
            fcn = ["calculateBeamStress", "calculateThermalResistance"];

            ctf = prodserver.mcp.build(fcn, ...
                archive=archive, ...
                wrapper=["None","None"], ...
                resource=resources, ...
                folder=tfolder.Folder);
            test.assertNotEmpty(ctf);
            test.assertEqual(exist(ctf, "file"), 2, ctf);

            test.endpoint = prodserver.mcp.deploy(ctf, test.host, test.port);
        end

    end

    methods (Test)

        function listResources(test)
            % 5 material + 1 wire-encoding = 6
            resourceList = prodserver.mcp.list(test.endpoint, "Resource");
            test.verifyEqual(numel(resourceList), 6, "Number of resources");
        end

        function readCatalogResource(test)
            catalogResult = prodserver.mcp.call(test.endpoint, ...
                prodserver.mcp.MCPConstants.ReadResourceTool, ...
                "mcp://materials/catalog");
            test.verifyTrue(isfield(catalogResult, "text"), ...
                "Catalog has no text field");
            test.verifyFalse(isempty(catalogResult.text), "Catalog is empty");
        end

        function toolsExist(test)
            test.verifyTrue( ...
                prodserver.mcp.exist(test.endpoint, "calculateBeamStress", "Tool"));
            test.verifyTrue( ...
                prodserver.mcp.exist(test.endpoint, "calculateThermalResistance", "Tool"));
        end

        function callBeamStress(test)
            F = 10000; L = 2.0; w = 0.05; h = 0.1;
            E = 68.9e9; sigma_y = 276e6;

            mcpResult = prodserver.mcp.call(test.endpoint, ...
                "calculateBeamStress", F, L, w, h, E, sigma_y);

            localResult = calculateBeamStress(F, L, w, h, E, sigma_y);

            test.verifyEqual(mcpResult.max_stress_Pa, ...
                localResult.max_stress_Pa, "max_stress_Pa", AbsTol=1e-6);
            test.verifyEqual(mcpResult.max_deflection_m, ...
                localResult.max_deflection_m, "max_deflection_m", AbsTol=1e-10);
            test.verifyEqual(mcpResult.safety_factor, ...
                localResult.safety_factor, "safety_factor", AbsTol=1e-6);
        end

        function callThermalResistance(test)
            thickness = 0.003; area = 0.04; k = 388;
            T_hot = 100; T_cold = 25;

            mcpResult = prodserver.mcp.call(test.endpoint, ...
                "calculateThermalResistance", thickness, area, k, ...
                T_hot, T_cold);

            localResult = calculateThermalResistance(thickness, area, k, ...
                T_hot, T_cold);

            test.verifyEqual(mcpResult.thermal_resistance_KperW, ...
                localResult.thermal_resistance_KperW, ...
                "thermal_resistance_KperW", AbsTol=1e-10);
            test.verifyEqual(mcpResult.heat_transfer_rate_W, ...
                localResult.heat_transfer_rate_W, ...
                "heat_transfer_rate_W", AbsTol=1e-6);
            test.verifyEqual(mcpResult.heat_flux_Wperm2, ...
                localResult.heat_flux_Wperm2, ...
                "heat_flux_Wperm2", AbsTol=1e-6);
            test.verifyEqual(mcpResult.midpoint_temperature_C, ...
                localResult.midpoint_temperature_C, ...
                "midpoint_temperature_C", AbsTol=1e-10);
        end

    end

    methods (Access=private)

        function resources = buildResources(test)
            catalog = struct( ...
                'uri', 'mcp://materials/catalog', ...
                'contents', fullfile(test.exampleFolder, "material_catalog.json"), ...
                'name', 'material_catalog', ...
                'title', 'Material Catalog', ...
                'description', 'List of all available engineering materials.', ...
                'mimeType', 'application/json');

            aluminum = struct( ...
                'uri', 'mcp://materials/aluminum_6061', ...
                'contents', fullfile(test.exampleFolder, "aluminum_6061.json"), ...
                'name', 'aluminum_6061', ...
                'title', 'Aluminum 6061-T6', ...
                'description', 'Aluminum 6061-T6 properties.', ...
                'mimeType', 'application/json');

            steel = struct( ...
                'uri', 'mcp://materials/steel_304', ...
                'contents', fullfile(test.exampleFolder, "steel_304.json"), ...
                'name', 'steel_304', ...
                'title', 'Stainless Steel 304', ...
                'description', 'Stainless Steel 304 properties.', ...
                'mimeType', 'application/json');

            titanium = struct( ...
                'uri', 'mcp://materials/titanium_ti6al4v', ...
                'contents', fullfile(test.exampleFolder, "titanium_ti6al4v.json"), ...
                'name', 'titanium_ti6al4v', ...
                'title', 'Titanium Ti-6Al-4V', ...
                'description', 'Titanium Ti-6Al-4V properties.', ...
                'mimeType', 'application/json');

            copper = struct( ...
                'uri', 'mcp://materials/copper_c110', ...
                'contents', fullfile(test.exampleFolder, "copper_c110.json"), ...
                'name', 'copper_c110', ...
                'title', 'Copper C110 (ETP)', ...
                'description', 'Copper C110 properties.', ...
                'mimeType', 'application/json');

            resources = [catalog, aluminum, steel, titanium, copper];
        end

    end
end
