function [xy,hue] = chaosfractal(N,sides,opts)
%chaosfractal Generate N 2D points of a chaos game fractal based on a
%polygon with the given number of sides. constraint influences the
%randomness of the chaos.
%
%The second output is the "color point" -- the point on the polygon towards 
%which the 2D point's generative vector points. Astonishingly, all the 
%points that "belong" to a given corner are generated by vectors that point 
%towards that corner. c is expressed in degrees, with the X-axis 
%representing 0 degrees.

% Copyright 2025, The MathWorks, Inc.

    arguments (Input)
        N (1,1) double % Number of points in the resulting fractal.
        sides (1,1) double % Number of sides of the chaos game fractal.
        % Optional argument R. The jump ratio for each point in the
        % fractal -- the proportion of the distance to the target corner at
        % which to place the next point.
        opts.R (1,1) double = 0
        % Corner selection constraint: 'None', "NoRepeat", "NotNeighbor"
        opts.Constraint (1,1) string = 'None'
    end
    
    arguments(Output)
        xy  double % Nx2 matrix. X,Y coordinates of the points of the fractal.
        hue double % Color angle of each point in the fractal, in degrees.
    end

    % Locate the corners evenly around the unit circle.
    theta = (2*pi) / sides;
    angle = (1:sides) * theta;
    corner = zeros(sides,2);
    corner(:,1) = cos(angle);
    corner(:,2) = sin(angle);
    degrees = rad2deg(angle);

    % How long to remember?
    H = 3;
    history = ones(1,H);

    % Distance to the next point.
    if opts.R == 0
        r = ( sides / (sides + 3) );
    else
        r = opts.R;
    end

    % Always start at the origin (constraining a random point to the
    % boundary of the polygon is hard).
    c(1) = 0; c(2) = 0;

    % Column matrix of 2D points. X = xy(1,:), Y = xy(2,:)
    xy = zeros(N,2);
    hue = zeros(N,1);
    for n = 1:N
        % Random corner, with constraint. history is last H corner choices,
        % with the most recent as history(1).
        k = constrain(sides,history,opts.Constraint);
        history(2:H) = history(1:end-1);
        history(1) = k;

        % Next point is r along the vector from cX,cY to x(k),y(k)
        c = c + ((corner(k,:) - c) * r);
        xy(n,:) = c;
        hue(n) = degrees(k);
    end

end

function k = constrain(sides,history,constraint)
    k = randi(sides);
    switch constraint
        case 'NotNeighbor'
        case 'NoRepeat'
            n = history(1);
            while k == n
                k = randi(sides);
            end
    end
end
